### PR TITLE
fix: Update pending changes not refreshing on new project

### LINKED ISSUE #4043: 🐛 Bug Report: Pending changes list is not updated when switching projects
### What happened?

When you view a project with pending changes, then switch the another project without pending changes, the list of pending changes is still showing the items from the previous project

in this screenshot, we can see changes on a service called "my service-1" while the current project does not include this service 
image

### What you expected to happen

The list of pending changes should be updated and show the changes of the current project, even when there are no changes in the newly selected project 

### How to reproduce

Open a project and make some changes (for example, created a service).
Before committing the changes, go to the Project List page, and select a new project. 

assuming there are no pending changes in the newly selected project, the list of pending changes still shows the items from the previous project. 

make a change in the new project (example, create a new service), and see how the list is now updated with the relevant changes. 

### Amplication version

1.0.2

### Environment

_No response_

### Are you willing to submit PR?

_No response_

### PR DESCRIPTION
**Pull request by TheLearneer**
Fixes #4043 

## PR Details
The issue has been fixed where pending changes of older project were retained in a newly started project with no pending changes.
The issues seemed to be the check being done in the `usePendingChanges` hook.

Currently the changes were not updated if the changes length was zero. This was causing the issue.

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

### CODE REVIEW

File: packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts [hunk 1]
```diff
@@ -28,8 +28,7 @@ const usePendingChanges = (currentProject: models.Project | undefined) => {
   });
 
   useEffect(() => {
-    if (!pendingChangesData || !pendingChangesData.pendingChanges.length)
-      return;
+    if (!pendingChangesData) return;
```
Comment (barshimi) [inline packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts:31]: instead of changing this condition and rerender the component, i suggest we add another useEffect that check the changes of currentProject (with the url project param) and accordingly refetch pending changes

Comment (TheLearneer) [reply packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts:31]: Sounds good to me. I am on it 🙌

Comment (TheLearneer) [reply packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts:31]: @barshimi I went through the logic once again, and I am not sure if refetching from another userEffect will be enough.
Because this specific block of code is responsible for setting the changes in the state.

Even if we refetch pending changes elsewhere we might still have to write the same code about setting state again, isn' it?

**Comment by yuval-hazaz** [comment]
@barshimi are you handling this one?

**Review by tupe12334 — APPROVED** [review]

**Comment by tupe12334** [comment]
@all-contributors please add @TheLearneer  for code

**Comment by yuval-hazaz** [comment]
@TheLearneer good catch! Well done, and thanks for contributing to Amplication 🚀
