### PR TITLE
Fix entity plural display name

### LINKED ISSUE #513: Client: incorrect entity plural display name when adding trailing spaces
**Describe the bug**
When creating a new entity with one or more spaces at the end of the name, the new entity plural display name is incorrect and includes the trailing spacing.

**To Reproduce**
1. Go to "Entities"
2. Click on "Create New"
3. Type in a new with a space at the end. e.g. "Team ".
4. See the plural display name of the new entity ("Team s")

**Expected behavior**
The plural display name should not include the trailing spaces

### PR DESCRIPTION
**Pull request by yuval-hazaz**
resolves #513

### CODE REVIEW

File: packages/amplication-client/src/Entity/NewEntity.tsx [hunk 1]
```diff
@@ -73,12 +73,14 @@ const NewEntity = ({ applicationId }: Props) => {
...
   const handleSubmit = useCallback(
     (data: CreateEntityType) => {
+      const displayName = data.displayName.trim();
       createEntity({
         variables: {
           data: {
             ...data,
-            name: pascalCase(data.displayName),
-            pluralDisplayName: generatePluralDisplayName(data.displayName),
+            displayName: displayName,
```
Comment (iddan) [inline packages/amplication-client/src/Entity/NewEntity.tsx:81]:
```suggestion
            displayName,
```

**Review by iddan — APPROVED** [review]
