### PR TITLE
Fix - navigating to the correct entity from a related field

### LINKED ISSUE #2693: 🐛 Bug Report: when navigating from entity page to anther the general settings in not selected automatically
### What happened?

from the entities page, when you navigate to an entity, the general setting tab is selected and you can see data,
but when from the entity itself, when you want to navigate to a related entity, the related entity state is not set on the general settings tab.

### What you expected to happen

I expect that the general setting tab would be selected while navigating from one entity to its related entity.

### How to reproduce

see the video

https://user-images.githubusercontent.com/39680385/167179005-7dd97c21-1035-43ee-b51c-aec7529f805a.mov

### Amplication version

0.12.6

### Environment

_No response_

### Are you willing to submit PR?

_No response_

### PR DESCRIPTION
**Pull request by sebabratakundu**
Issue Number: #2693 

## PR Details

- User will redirect to general tab of an selected entity while navigating from one entity to its related entity.

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

Closes #2693

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

### CODE REVIEW

File: packages/amplication-client/src/Entity/RelatedEntityFieldField.tsx [hunk 1]
```diff
@@ -37,7 +44,7 @@ const RelatedEntityFieldField = ({ entityDisplayName }: Props) => {
         <EntityRelationFieldsChart
           fixInPlace={false}
           applicationId={data.entity.appId}
-          entityId={data.entity.id}
+          entityId={entity}
```
Comment (yuval-hazaz) [inline packages/amplication-client/src/Entity/RelatedEntityFieldField.tsx:47]: I dont think this is the right fix for this issue. 
I expected to see the fix in the component `amplication-client/src/Entity/EntityRelationFieldsChart.tsx`
The component includes 4 links, only the first pair is not working correctly - the second one is fine. I do not expect to see a change of the component props, rather just a change in how the component builds the links internally

**Review by yuval-hazaz — CHANGES_REQUESTED** [review]

File: packages/amplication-client/src/Entity/RelatedEntityFieldField.tsx (hunk 1 above)
Comment (sebabratakundu) [reply packages/amplication-client/src/Entity/RelatedEntityFieldField.tsx:47]: Ok, will do the changes

**Review by yuval-hazaz — APPROVED** [review]

**Comment by yuval-hazaz** [comment]
@tupe12334 please merge to next release
