### PR TITLE
abort generate code when user turn it on

### LINKED ISSUE #3954: 🐛 Bug Report: When a plugin event fails, there is no indication of a failure
### What happened?

When a plugin event fails, there is no indication of a failure.

For example, when a user installs the MySQL plugin, and on one of the entities, he has a field with the `MultiSelectOptionSet` type. Prisma's MyQL provider doesn't support an array of primitives. Therefore the plugin event fails, **but** there is no indication of a failure on the build page, as the plugin wrapper function doesn't handle these kind of errors

Screen Shot 2022-09-24 at 21 19 42

### What you expected to happen

I expect the build to fail

### How to reproduce

 - create a project with a service
 - install the MySQL plugin on this service
 - create a field type `MultiSelectOptionSet` on of the entities
 - Click on build

### Amplication version

next

### Environment

_No response_

### Are you willing to submit PR?

_No response_

### PR DESCRIPTION
**Pull request by barshimi**
Close #3954 

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

File: packages/amplication-data-service-generator/src/plugin-wrapper.ts [hunk 1]
```diff
@@ -91,7 +92,7 @@ const pluginWrapper: PluginWrapper = async (
         error
       )}`,
     });
-    return [];
+    return context.utils.abortGeneration ? process.exit(0) : [];
```
Comment (yuval-hazaz) [inline packages/amplication-data-service-generator/src/plugin-wrapper.ts:95]: I think we should abort more gracefully and add a message to the logger

instead of using a boolean, we can use a function context.abortGeneration(message)

**Review by yuval-hazaz — CHANGES_REQUESTED** [review]
