### PR TITLE
Commit & discard modals

### LINKED ISSUE #536: Client: The commit button should be disabled by default
**Describe the bug**
The commit button should be disabled by default

**To Reproduce**
1. Go to 'pending changed'
2. Click on 'commit changes button'
4. The commit button in the modal pop-up should be disabled until the user adds a description.

### PR DESCRIPTION
**Pull request by yuval-hazaz**
resolve #536

### CODE REVIEW

File: packages/amplication-client/src/VersionControl/Commit.tsx [hunk 1]
```diff
@@ -66,36 +69,46 @@ const Commit = ({ applicationId, onComplete }: Props) => {
...
-            buttonStyle={EnumButtonStyle.Primary}
-            eventData={{
-              eventName: "commit",
-            }}
-          >
-            Commit
-          </Button>
-        </Form>
+        {(formik) => {
+          return (
```
Comment (iddan) [inline packages/amplication-client/src/VersionControl/Commit.tsx:84]: No need for brackets

**Review by iddan — APPROVED** [review]
