### PR TITLE
Hotfix/json and null

### LINKED ISSUE #2092: E2E tests are failing - release 0.11.0
### What happened?

GitHub `CI `Workflow is failing in `build` job in `Run test data service's tests` step.

### What you expected to happen

FAIL src/user/base/user.controller.base.spec.ts
  ● Test suite failed to run

    src/user/base/user.controller.base.ts:63:7 - error TS2322: Type '{ manager: { connect: UserWhereUniqueInput; } | undefined; username: string; password: string; roles: string[]; name: string; bio: string; email: string; age: number; birthDate: Date; ... 5 more ...; extendedProperties: JsonValue; }' is not assignable to type '(Without<UserCreateInput, UserUncheckedCreateInput> & UserUncheckedCreateInput) | (Without<...> & UserCreateInput)'.
      Type '{ manager: { connect: UserWhereUniqueInput; } | undefined; username: string; password: string; roles: string[]; name: string; bio: string; email: string; age: number; birthDate: Date; ... 5 more ...; extendedProperties: JsonValue; }' is not assignable to type 'Without<UserUncheckedCreateInput, UserCreateInput> & UserCreateInput'.
        Type '{ manager: { connect: UserWhereUniqueInput; } | undefined; username: string; password: string; roles: string[]; name: string; bio: string; email: string; age: number; birthDate: Date; ... 5 more ...; extendedProperties: JsonValue; }' is not assignable to type 'UserCreateInput'.
          Types of property 'extendedProperties' are incompatible.
            Type 'JsonValue' is not assignable to type 'InputJsonValue'.
              Type 'null' is not assignable to type 'InputJsonValue'.

    63       data: {
             ~~~~

      node_modules/.prisma/client/index.d.ts:1933:5
        1933     data: XOR<UserCreateInput, UserUncheckedCreateInput>
                 ~~~~
        The expected type comes from property 'data' which is declared here on type '{ select?: UserSelect | null | undefined; include?: UserInclude | null | undefined; data: (Without<UserCreateInput, UserUncheckedCreateInput> & UserUncheckedCreateInput) | (Without<...> & UserCreateInput); }'
    src/user/base/user.controller.base.ts:128:49 - error TS2345: Argument of type '{ select: { username: true; roles: true; id: true; name: true; bio: true; email: true; age: true; birthDate: true; score: true; manager: { select: { id: true; }; }; interests: true; priority: true; isCurious: true; location: true; extendedProperties: true; }; where?: UserWhereInput | undefined; orderBy?: UserOrderBy...' is not assignable to parameter of type '{ select?: UserSelect | null | undefined; include?: UserInclude | null | undefined; where?: UserWhereInput | undefined; orderBy?: Enumerable<UserOrderByWithRelationInput> | undefined; cursor?: UserWhereUniqueInput | undefined; take?: number | undefined; skip?: number | undefined; distinct?: Enumerable<...> | undefin...'.
      Types of property 'where' are incompatible.
        Type 'import("/home/runner/work/amplication-hosted/amplication-hosted/packages/amplication-data-service-generator/generated/server/src/user/base/UserWhereInput").UserWhereInput | undefined' is not assignable to type 'import("/home/runner/work/amplication-hosted/amplication-hosted/packages/amplication-data-service-generator/generated/server/node_modules/.prisma/client/index").Prisma.UserWhereInput | undefined'.
          Type 'import("/home/runner/work/amplication-hosted/amplication-hosted/packages/amplication-data-service-generator/generated/server/src/user/base/UserWhereInput").UserWhereInput' is not assignable to type 'import("/home/runner/work/amplication-hosted/amplication-hosted/packages/amplication-data-service-generator/generated/server/node_modules/.prisma/client/index").Prisma.UserWhereInput'.
            Types of property 'extendedProperties' are incompatible.
              Type 'JsonNullableFilter | undefined' is not assignable to type 'JsonFilter | undefined'.
                Type 'JsonNullableFilter' is not assignable to type 'JsonFilter | undefined'.
                  Type 'JsonNullableFilter' is not assignable to type '{ equals?: string | number | boolean | InputJsonObject | InputJsonArray | undefined; not?: string | number | boolean | InputJsonObject | InputJsonArray | undefined; }'.
                    Types of property 'equals' are incompatible.
                      Type 'JsonValue | undefined' is not assignable to type 'string | number | boolean | InputJsonObject | InputJsonArray | undefined'.
                        Type 'null' is not assignable to type 'string | number | boolean | InputJsonObject | InputJsonArray | undefined'.

    128     const results = await this.service.findMany({
                                                        ~
    129       ...args,
        ~~~~~~~~~~~~~~
    ... 
    152       },
        ~~~~~~~~
    153     });
        ~~~~~
    src/user/base/user.controller.base.ts:256:9 - error TS2322: Type '{ manager: { connect: UserWhereUniqueInput; } | undefined; username?: string | undefined; password?: string | undefined; roles?: string[] | undefined; name?: string | undefined; ... 9 more ...; extendedProperties?: JsonValue | undefined; }' is not assignable to type '(Without<UserUpdateInput, UserUncheckedUpdateInput> & UserUncheckedUpdateInput) | (Without<...> & UserUpdateInput)'.
      Type '{ manager: { connect: UserWhereUniqueInput; } | undefined; username?: string | undefined; password?: string | undefined; roles?: string[] | undefined; name?: string | undefined; ... 9 more ...; extendedProperties?: JsonValue | undefined; }' is not assignable to type 'Without<UserUncheckedUpdateInput, UserUpdateInput> & UserUpdateInput'.
        Type '{ manager: { connect: UserWhereUniqueInput; } | undefined; username?: string | undefined; password?: string | undefined; roles?: string[] | undefined; name?: string | undefined; ... 9 more ...; extendedProperties?: JsonValue | undefined; }' is not assignable to type 'UserUpdateInput'.
          Types of property 'extendedProperties' are incompatible.
            Type 'JsonValue | undefined' is not assignable to type 'InputJsonValue | undefined'.
              Type 'null' is not assignable to type 'InputJsonValue | undefined'.

    256         data: {
                ~~~~

      node_modules/.prisma/client/index.d.ts:1964:5
        1964     data: XOR<UserUpdateInput, UserUncheckedUpdateInput>
                 ~~~~
        The expected type comes from property 'data' which is declared here on type '{ select?: UserSelect | null | undefined; include?: UserInclude | null | undefined; data: (Without<UserUpdateInput, UserUncheckedUpdateInput> & UserUncheckedUpdateInput) | (Without<...> & UserUpdateInput); where: UserWhereUniqueInput; }'
    src/user/base/user.controller.base.ts:382:7 - error TS2322: Type 'import("/home/runner/work/amplication-hosted/amplication-hosted/packages/amplication-data-service-generator/generated/server/src/user/base/UserWhereInput").UserWhereInput' is not assignable to type 'import("/home/runner/work/amplication-hosted/amplication-hosted/packages/amplication-data-service-generator/generated/server/node_modules/.prisma/client/index").Prisma.UserWhereInput'.

    382       where: query,
              ~~~~~

      node_modules/.prisma/client/index.d.ts:1882:5
        1882     where?: UserWhereInput
                 ~~~~~
        The expected type comes from property 'where' which is declared here on type 'UserFindManyArgs'

FAIL src/organization/base/organization.controller.base.spec.ts
  ● Test suite failed to run

    src/organization/base/organization.controller.base.ts:283:7 - error TS2322: Type 'import("/home/runner/work/amplication-hosted/amplication-hosted/packages/amplication-data-service-generator/generated/server/src/user/base/UserWhereInput").UserWhereInput' is not assignable to type 'import("/home/runner/work/amplication-hosted/amplication-hosted/packages/amplication-data-service-generator/generated/server/node_modules/.prisma/client/index").Prisma.UserWhereInput'.
      Types of property 'extendedProperties' are incompatible.
        Type 'JsonNullableFilter | undefined' is not assignable to type 'JsonFilter | undefined'.
          Type 'JsonNullableFilter' is not assignable to type 'JsonFilter | undefined'.
            Type 'JsonNullableFilter' is not assignable to type '{ equals?: string | number | boolean | InputJsonObject | InputJsonArray | undefined; not?: string | number | boolean | InputJsonObject | InputJsonArray | undefined; }'.
              Types of property 'equals' are incompatible.
                Type 'JsonValue | undefined' is not assignable to type 'string | number | boolean | InputJsonObject | InputJsonArray | undefined'.
                  Type 'null' is not assignable to type 'string | number | boolean | InputJsonObject | InputJsonArray | undefined'.

    283       where: query,
              ~~~~~

      node_modules/.prisma/client/index.d.ts:1882:5
        1882     where?: UserWhereInput
                 ~~~~~
        The expected type comes from property 'where' which is declared here on type 'UserFindManyArgs'


### How to reproduce

Run CI workflow in the master branch - release 0.11.0

### Amplication version

0.11.0

### Environment

node: 16.3.1
npm: 8.2.1
Platform: GitHub Actions
OS: Ubuntu-20

### Anything else

_No response_

### Are you willing to submit PR?

_No response_

### Code of Conduct

I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tupe12334**
resolve #2092

### CODE REVIEW

File: packages/amplication-data-service-generator/src/admin/static/src/util/JsonFilter.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+import { JsonValue } from "type-fest";
+export class JsonFilter {
+  equals?: Omit<JsonValue, "null">;
```
Comment (yuval-hazaz) [inline packages/amplication-data-service-generator/src/admin/static/src/util/JsonFilter.ts:3]: Use the new type

**Review by yuval-hazaz — CHANGES_REQUESTED** [review]

File: packages/amplication-server/prisma/migrations/20211230120749_prisma_v3_renaming/migration.sql [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+ALTER INDEX "Environment.appId_name_unique" RENAME TO "Environment_appId_name_key";
+
+-- RenameIndex
+ALTER INDEX "User.accountId_workspaceId_unique" RENAME TO "User_accountId_workspaceId_key";
+
+-- RenameIndex
+ALTER INDEX "UserRole.userId_role_unique" RENAME TO "UserRole_userId_role_key";
+
+-- RenameIndex
+ALTER INDEX "Workspace.name_unique" RENAME TO "Workspace_name_key";
```
Comment (yuval-hazaz) [inline packages/amplication-server/prisma/migrations/20211230120749_prisma_v3_renaming/migration.sql:71]: Why all these changes are needed?

**Review by yuval-hazaz — CHANGES_REQUESTED** [review]

File: packages/amplication-server/prisma/migrations/20211230120749_prisma_v3_renaming/migration.sql (hunk 2 above)
Comment (mshidlov) [reply packages/amplication-server/prisma/migrations/20211230120749_prisma_v3_renaming/migration.sql:71]: **Option 1: I want to maintain my existing constraint and index names**
If you want to keep your database unchanged and keep the existing names for constraints and indexes you need to pull them into your schema so Prisma is aware of them.
**Option 2: I want to use Prisma's default constraint and index names**
If you want to keep your Prisma Schema clean and if you have no reasons preventing you from renaming constraints and indexes in your database, then you can create a migration to update the names.

Comment (mshidlov) [reply packages/amplication-server/prisma/migrations/20211230120749_prisma_v3_renaming/migration.sql:71]: The standard names for indexes in PostgreSQL are:

`{tablename}_{columnname(s)}_{suffix}`

where the suffix is one of the following:

`pkey` for a Primary Key constraint
`key`f or a Unique constraint
`excl` for an Exclusion constraint
`idx` for any other kind of index
`fkey` for a Foreign key
`check` for a Check constraint
Standard suffix for sequences is

`seq` for all sequences

from: 
- [stackoverflow](https://stackoverflow.com/questions/4107915/postgresql-default-constraint-names/4108266#4108266)
- [postgresql manual](https://www.postgresql.org/docs/current/sql-altertable.html)

Comment (mshidlov) [reply packages/amplication-server/prisma/migrations/20211230120749_prisma_v3_renaming/migration.sql:71]: This can be removed for now

**Comment by mshidlov** [comment]
**Option 1: I want to maintain my existing constraint and index names**
If you want to keep your database unchanged and keep the existing names for constraints and indexes you need to pull them into your schema so Prisma is aware of them.
**Option 2: I want to use Prisma's default constraint and index names**
If you want to keep your Prisma Schema clean and if you have no reasons preventing you from renaming constraints and indexes in your database, then you can create a migration to update the names.



The standard names for indexes in PostgreSQL are:

`{tablename}_{columnname(s)}_{suffix}`

where the suffix is one of the following:

`pkey` for a Primary Key constraint
`key`f or a Unique constraint
`excl` for an Exclusion constraint
`idx` for any other kind of index
`fkey` for a Foreign key
`check` for a Check constraint
Standard suffix for sequences is

`seq` for all sequences

from: 
- [stackoverflow](https://stackoverflow.com/questions/4107915/postgresql-default-constraint-names/4108266#4108266)
- [postgresql manual](https://www.postgresql.org/docs/current/sql-altertable.html)




**Currently we are doing option 1**

File: packages/amplication-server/prisma/migrations/20211230120749_prisma_v3_renaming/migration.sql (hunk 2 above)
Comment (yuval-hazaz) [reply packages/amplication-server/prisma/migrations/20211230120749_prisma_v3_renaming/migration.sql:71]: Just wondering what made us do it now, no reason to pull it out.
IIUC this was generated by the new Prisma version? 

Anyway, it would have been better to use a separate PR with explanation for history tracking.

My two cents, your call

Comment (mshidlov) [reply packages/amplication-server/prisma/migrations/20211230120749_prisma_v3_renaming/migration.sql]: Yes, this is generated by the new Prisma version. This change can happen in any time in the future, so I don't see any reason to do it now

File: packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts [hunk 3]
```diff
@@ -47,7 +46,9 @@ const PRISMA_SCALAR_TO_TYPE: {
   [ScalarType.Float]: builders.tsNumberKeyword(),
   [ScalarType.Int]: builders.tsNumberKeyword(),
   [ScalarType.String]: builders.tsStringKeyword(),
-  [ScalarType.Json]: builders.tsTypeReference(JSON_VALUE_ID),
+  [ScalarType.Json]: builders.tsTypeReference(
+    builders.identifier("InputJsonValue")
```
Comment (tupe12334) [inline packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts:50]: change to const

File: packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts [hunk 4]
```diff
@@ -449,3 +470,14 @@ export function createFieldValueTypeFromPrismaField(
     return [builders.tsTypeReference(builders.identifier(prismaField.type))];
   }
 }
+
+function getFilterASTIdentifier(
+  isRequired: boolean,
+  type: ScalarType
+): namedTypes.Identifier {
+  if (isRequired || type === "Json") {
```
Comment (tupe12334) [inline packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts:478]: use enum insted

File: packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts [hunk 5]
```diff
@@ -389,9 +400,16 @@ export function createFieldValueTypeFromPrismaField(
...
-  isQuery: boolean
+  isQuery: boolean,
+  isObjectType: boolean
 ): TSTypeKind[] {
-  if (!prismaField.isRequired && !isQuery) {
+  // add  "| null" to the end of the type
+  if (
+    !prismaField.isRequired &&
+    !isQuery &&
+    !(prismaField.type === "Json") // json property cant be null
```
Comment (tupe12334) [inline packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts:410]: use enum insted

**Review by mshidlov — APPROVED** [review]
